### ISSUE TITLE
Cringe

### ISSUE THREAD

**Issue by ayushsinghal12** [aryanbaburajan/aryanbaburajan.github.io#1]
My portfolio better

**Comment by aryanbaburajan** [comment]
Your portfolio:
- Inconsistent font
- Used stock photo of dude in front of a computer that's not you
- Bad color scheme
<img width="943" alt="image" src="https://user-images.githubusercontent.com/51789606/236154582-1c8c94b5-fac3-498f-a7bb-96d0321e5fb4.png">
- Unconfident and unprofessional wording
- Mentioning of your online nickname "Test Subject" on a portfolio
- Mentioning known programming languages due to lack of mentionworthy projects
- (Very) bad thumbnail design on all your projects
- Thumbnail of "SNEKIRUHS" stolen from a popular scratch game

Fix these, if you will :)
